### ISSUE TITLE
Flathub / AppImage support

### ISSUE THREAD

**Issue by icavalheiro** [diddlesnaps/fakecam#3]
Hi, can you consider publishing this package to Flathub or adding AppImage support?
Snaps are great but not all systems come with it preinstalled (specially pop_os and elementary).

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines
- Decentralized

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

**Comment by skellat** [comment]
> Providing an [AppImage](http://appimage.org/) would have, among others, these advantages

Considering who the author of the software happens to be as well as their prominence within the snapcraft community you're engaging in an act of utter futility.  This isn't going to happen.

**Comment by probonopd** [comment]
The original poster requested Flatpak or AppImage. You say the author does Snap. So why not have all three? It's really not an either-or...

**Comment by mattiaswerner** [comment]
It's not an either or. But it is a question of how much one individual developer is willing and able to support. You say "all three", but there are more packaging systems out there. Why should rpm not be counted?

Long story short, if you want to get uptake in another format than the developer provides you need to find someone who is willing to take on supporting it. As the source is freely available that makes it a lot easier.

**Comment by skellat** [comment]
> The original poster requested Flatpak or AppImage. You say the author does Snap. So why not have all three? It's really not an either-or...

The problem there is that you are making a tremendous assumption as to your entitlement.  You are owed nothing.  The author could have just as easily thrown the code over the wall without packaging.  That a choice was made to use just snaps reflects a choice of how to direct time and resources.

It is far less intensive for potential users to just [install snapd according to the directions for their distribution](https://snapcraft.io/docs/installing-snapd).
